//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSR7_Dem.DataBase
{
    using System;
    using System.Collections.Generic;
    using System.IO;

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int ID { get; set; }
        public string ProductName { get; set; }
        public string ProductDescription { get; set; }
        public string ProductCategory { get; set; }
        public byte[] ProductPhoto { get; set; }
        public string ProductManufacturer { get; set; }
        public decimal ProductCost { get; set; }
        public Nullable<byte> ProductDiscountAmount { get; set; }
        public int ProductQuantityInStock { get; set; }
        public string ProductStatus { get; set; }
        public string ProductPath { get; set; }


        public string ProductPathView
        {
            get => ProductPath == null ? Directory.GetCurrentDirectory()+@"\Images\picture.png" :
                Directory.GetCurrentDirectory() + @"\Images\" + ProductPath.Replace("\r\n",String.Empty);
        }
        public string ProductManufacturerView
        {
            get => "Производитель: " + ProductManufacturer;
        }
        public string ProductCostView
        {
            get => "Цена:" + ProductCost.ToString();
        }
        public string ProductQuantity
        {
            get => ProductQuantityInStock > 0 ? "Имеются в наличии" : "Отсутствуют на складе";
        }
        

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
    }
}
